CREATE SCHEMA TIFORMS;


CREATE TABLE TIFORMS.FORM (
    ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE TIFORMS.FORMFIELD (
    ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    FORM_ID INTEGER NOT NULL,
    LABEL VARCHAR(200) NOT NULL,
    FIELD_TYPE VARCHAR(50) NOT NULL,
    REQUIRED SMALLINT DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (FORM_ID) REFERENCES TIFORMS.FORM(ID) ON DELETE CASCADE
);


CREATE TABLE TIFORMS.FORMSUBMISSION (
    ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    FORM_ID INTEGER NOT NULL,
    DATA CLOB,  -- JSON serializado como texto
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (FORM_ID) REFERENCES TIFORMS.FORM(ID) ON DELETE CASCADE
);

CREATE TABLE TIFORMS.FORM_FORMFIELDS (
    FORM_ID INTEGER NOT NULL,
    FORMFIELD_ID INTEGER NOT NULL,
    PRIMARY KEY (FORM_ID, FORMFIELD_ID),
    FOREIGN KEY (FORM_ID) REFERENCES TIFORMS.FORM(ID) ON DELETE CASCADE,
    FOREIGN KEY (FORMFIELD_ID) REFERENCES TIFORMS.FORMFIELD(ID) ON DELETE CASCADE
);

